spring:
  application.name: kale-kaj-driver

  ai:
    ollama:
      init:
        pull-model-strategy: always
      chat:
        options:
          model: llava
    vertex:
      ai:
        gemini:
          project-id: ai-circle-2025-cluster-34390
          location: europe-north1
#          location: us-east5
          chat:
            options:
              model: gemini-2.5-pro
          transport: rest
  main:
    banner-mode: off

  http:
    client:
      factory: jdk
