spring:
  application.name: kale-kaj-driver

  ai:
    ollama:
      init:
        pull-model-strategy: always
      chat:
        options:
          model: llava:7b
#          model: deepseek-r1:8b
    vertex:
      ai:
        gemini:
          project-id: ai-circle-2025-cluster-34390
          location: europe-north1
          chat:
            options:
              model: gemini-1.5-flash
              temperature: 0.1
  main:
    banner-mode: off

  http:
    client:
      factory: jdk
